{
    "name": "Multiple Product Barcodes Management & Barcode Scanning for Odoo Inventory",
    "version": "18.0.1.5.0",
    "author": "Vizion Tools",
    "website": "https://viziontools.com/",
    "support": "support@viziontools.com",
    "license": "OPL-1",
    "price": 5.00,
    "currency": "USD",
    "category": "Inventory/Inventory",
    "application": True,
    "installable": True,
    "images": [
        "static/description/main_screenshot.png",
        "static/description/screenshot_1.png",
    ],
    "summary": "Add unlimited EAN-13, UPC-A, Code 128 & QR barcodes per product or variant - scan, search and import them across Inventory, POS, Purchase & Sales.",
    "depends": [
        "product",
        "sale",
        "purchase",
        "stock",
    ],
    "data": [
        "security/ir.model.access.csv",
        "wizard/multiply_barcode_wizard.xml",
        "views/product_template_views.xml",
        "views/stock_picking_views.xml",
    ],
}
